# ETL Metadata Sitios Google Maps

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import json

## 1. Analizamos la estructura de los archivos json.

Observamos la estructura de los archivos .json, especialmente si son las mismas keys en cada archivo json.

In [ ]:
df_metadata_1 = pd.read_json('/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 1.json', lines=True)
df_metadata_1.iloc[0]

name                                                  Porter Pharmacy
address             Porter Pharmacy, 129 N Second St, Cochran, GA ...
gmap_id                         0x88f16e41928ff687:0x883dad4fd048e8f8
description                                                      None
latitude                                                      32.3883
longitude                                                    -83.3571
category                                                   [Pharmacy]
avg_rating                                                        4.9
num_of_reviews                                                     16
price                                                            None
hours               [[Friday, 8AM–6PM], [Saturday, 8AM–12PM], [Sun...
MISC                {'Service options': ['In-store shopping', 'Sam...
state                                               Open ⋅ Closes 6PM
relative_results    [0x88f16e41929435cf:0x5b2532a2885e9ef6, 0x88f1...
url                 https://www.google.com/maps/place//data=!4m2!3...
Name: 0, dtype: object

In [ ]:
df_metadata_5 = pd.read_json('/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 5.json', lines=True)
df_metadata_5.iloc[0]

name                                                  Porter Pharmacy
address             Porter Pharmacy, 129 N Second St, Cochran, GA ...
gmap_id                         0x88f16e41928ff687:0x883dad4fd048e8f8
description                                                      None
latitude                                                      32.3883
longitude                                                    -83.3571
category                                                   [Pharmacy]
avg_rating                                                        4.9
num_of_reviews                                                     16
price                                                            None
hours               [[Friday, 8AM–6PM], [Saturday, 8AM–12PM], [Sun...
MISC                {'Service options': ['In-store shopping', 'Sam...
state                                               Open ⋅ Closes 6PM
relative_results    [0x88f16e41929435cf:0x5b2532a2885e9ef6, 0x88f1...
url                 https://www.google.com/maps/place//data=!4m2!3...
Name: 0, dtype: object

In [ ]:
df_metadata_11 = pd.read_json('/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 11.json', lines=True)
df_metadata_11.iloc[0]

name                                                  Porter Pharmacy
address             Porter Pharmacy, 129 N Second St, Cochran, GA ...
gmap_id                         0x88f16e41928ff687:0x883dad4fd048e8f8
description                                                      None
latitude                                                      32.3883
longitude                                                    -83.3571
category                                                   [Pharmacy]
avg_rating                                                        4.9
num_of_reviews                                                     16
price                                                            None
hours               [[Friday, 8AM–6PM], [Saturday, 8AM–12PM], [Sun...
MISC                {'Service options': ['In-store shopping', 'Sam...
state                                               Open ⋅ Closes 6PM
relative_results    [0x88f16e41929435cf:0x5b2532a2885e9ef6, 0x88f1...
url                 https://www.google.com/maps/place//data=!4m2!3...
Name: 0, dtype: object

### Las keys son similares en todos los json files, ahora intentamos juntar todos los archivos .json en un solo DataFrame.

In [ ]:
file_path1 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 1.json'
df1 = pd.read_json(file_path1, lines=True)

file_path2 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 2.json'
df2 = pd.read_json(file_path2, lines=True)

file_path3 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 3.json'
df3 = pd.read_json(file_path3, lines=True)

file_path4 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 4.json'
df4 = pd.read_json(file_path4, lines=True)

file_path5 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 5.json'
df5 = pd.read_json(file_path5, lines=True)

file_path6 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 6.json'
df6 = pd.read_json(file_path6, lines=True)

'''
file_path7 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 7.json'
df7 = pd.read_json(file_path7, lines=True)

file_path8 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 8.json'
df8 = pd.read_json(file_path8, lines=True)

file_path9 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 9.json'
df9 = pd.read_json(file_path9, lines=True)

file_path10 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 10.json'
df10 = pd.read_json(file_path10, lines=True)

file_path11 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 11.json'
df11 = pd.read_json(file_path11, lines=True)
'''

In [ ]:
df_list1 = [df1, df2, df3, df4, df5, df6] #df7, df8, df9, df10, df11]
df_metadata_sitios_google1 = pd.concat(df_list1, ignore_index=True)
df_metadata_sitios_google1.to_csv('/content/drive/MyDrive/Otros/df_metadata_sitios_google1.csv', index=False)

In [ ]:
file_path7 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 7.json'
df7 = pd.read_json(file_path7, lines=True)

file_path8 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 8.json'
df8 = pd.read_json(file_path8, lines=True)

file_path9 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 9.json'
df9 = pd.read_json(file_path9, lines=True)

file_path10 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 10.json'
df10 = pd.read_json(file_path10, lines=True)

file_path11 = '/content/drive/MyDrive/google_maps/metadata_sitios/Copia de 11.json'
df11 = pd.read_json(file_path11, lines=True)

In [ ]:
df_list2 = [df7, df8, df9, df10, df11]
df_metadata_sitios_google2 = pd.concat(df_list2, ignore_index=True)
df_metadata_sitios_google2.to_csv('/content/drive/MyDrive/Otros/df_metadata_sitios_google2.csv', index=False)

### Unificamos los csv de los archivos guardados.

In [ ]:
df_1_metadata = pd.read_csv('/content/drive/MyDrive/Otros/df_metadata_sitios_google1.csv')

In [ ]:
df_2_metadata = pd.read_csv('/content/drive/MyDrive/Otros/df_metadata_sitios_google2.csv')

In [ ]:
df_list_final = [df_1_metadata,df_2_metadata]
df_metada = pd.concat(df_list_final, ignore_index=True)

In [ ]:
df_metada = df_metada.drop(columns=['relative_results','url'])

In [ ]:
df_metada = df_metada.drop_duplicates()

### Guardamos el archivo csv unificado.

In [ ]:
df_metada.to_csv('/content/drive/MyDrive/Otros/googlemaps_metadata_sitios.csv', index=False)

###  Cargamos el csv unificado y filtramos para Florida usando la columna address.

In [ ]:
import gc
gc.collect() # Sirve para borrar algo despues de haberlo corrido

import pandas as pd

df_metada = pd.read_csv('/content/drive/MyDrive/Otros/googlemaps_metadata_sitios.csv')

In [ ]:
df_metada.iloc[105]

name                                              Brian Shaheen, MD
address           Brian Shaheen, MD, 2421 Thomas Dr, Panama City...
gmap_id                       0x8893863ea87bd5dd:0x9383ebf973e74abb
description                                                     NaN
latitude                                                  30.159982
longitude                                                -85.752277
category          ['Family practice physician', 'General practit...
avg_rating                                                      4.2
num_of_reviews                                                   18
price                                                           NaN
hours             [['Thursday', '8AM–5PM'], ['Friday', '8AM–5PM'...
MISC              {'Service options': ['Online care'], 'Accessib...
state                                             Open ⋅ Closes 5PM
Name: 105, dtype: object

## RESUMIMOS LO ANTERIOR(UNIFICAR Y CARGAR LOS .JSON) CON LAS SIGUIENTES FUNCIONES:
(Eduardo)

In [28]:
# Lee y guarda en archivos CSV temporales
import pandas as pd
import gc
count = 1
while count <= 11:
  df_metadata_1 = pd.read_json('/content/drive/MyDrive/google_maps/metadata_sitios/Copia de ' + str(count) + '.json', lines=True)
  df_metadata_1.to_csv('/content/drive/MyDrive/Otros/df_borrar_google_'+ str(count) + '.csv', index=False)
  count = count + 1
gc.collect()

0

In [29]:
#Lee CSV y carga a dataframes, y concatena al dataframe origen que contendra todo df_metadata_origen
count = 1
df_metadata_origen = pd.DataFrame()
while count <= 11:
  df_metadata_1 = pd.read_csv('/content/drive/MyDrive/Otros/df_borrar_google_'+ str(count) + '.csv')
  df_metadata_origen = pd.concat([df_metadata_origen, df_metadata_1], ignore_index=True)
  count = count + 1
gc.collect()

0

In [32]:
df_metada = df_metadata_origen.copy()

df_metada = df_metada.drop(columns=['relative_results','url'])
df_metada = df_metada.drop_duplicates()

### Extraeremos datos de la columna:

 - Address

### Desanidaremos las columnas:

 - Category

 - MISC

 - Hours

## 2. Columna Address

#### Filtramos para Florida

In [33]:
print(df_metada.iloc[14]['address'])
print(type(df_metada.iloc[14]['address']))

NTK OUTDOOR, 2315 NW 107th Ave #1B18, Miami, FL 33172
<class 'str'>

In [34]:
metdat_florida = df_metada[df_metada['address'].str.contains('FL', na=False, case=True)]
metdat_florida = metdat_florida.copy()
metdat_florida.head(3)

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state
14,NTK OUTDOOR,"NTK OUTDOOR, 2315 NW 107th Ave #1B18, Miami, F...",0x88d9beb4fe0532c1:0xef0555c169299d6,NaN,25.795204,-80.366038,['Corporate office'],5.0,35,NaN,"[['Thursday', '9AM–6PM'], ['Friday', '9AM–6PM'...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 6PM
45,Cruises Inc. - Connie Stewart,"Cruises Inc. - Connie Stewart, 6602 52nd Ln, P...",0x88c2e49b79f06c31:0x4ed8c8ce27e926e0,NaN,27.832187,-82.704805,['Cruise agency'],5.0,2,NaN,"[['Thursday', '9AM–5PM'], ['Friday', '9AM–5PM'...",NaN,Open ⋅ Closes 5PM
56,Seminole Family Restaurant,"Seminole Family Restaurant, 6864 Seminole Blvd...",0x88c2fb8614e57ce9:0x40b51628875ad6e9,NaN,27.834885,-82.787419,NaN,3.6,8,$$,NaN,NaN,NaN

### Extraemos ciudad(city), stado (states) y codigo postal (postal_code)

In [35]:
regex = r'.+,\s*(?P<city>[^,]+),\s*(?P<states>[^\s]+)\s+(?P<postal_code>\S+)'
new_df = metdat_florida['address'].str.extract(regex) #metdat_florida por fd_metada

metdat_florida = metdat_florida.join(new_df,lsuffix='_original', rsuffix='_new')

metdat_florida.head(3)

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,city,states,postal_code
14,NTK OUTDOOR,"NTK OUTDOOR, 2315 NW 107th Ave #1B18, Miami, F...",0x88d9beb4fe0532c1:0xef0555c169299d6,NaN,25.795204,-80.366038,['Corporate office'],5.0,35,NaN,"[['Thursday', '9AM–6PM'], ['Friday', '9AM–6PM'...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 6PM,Miami,FL,33172
45,Cruises Inc. - Connie Stewart,"Cruises Inc. - Connie Stewart, 6602 52nd Ln, P...",0x88c2e49b79f06c31:0x4ed8c8ce27e926e0,NaN,27.832187,-82.704805,['Cruise agency'],5.0,2,NaN,"[['Thursday', '9AM–5PM'], ['Friday', '9AM–5PM'...",NaN,Open ⋅ Closes 5PM,Pinellas Park,FL,33781
56,Seminole Family Restaurant,"Seminole Family Restaurant, 6864 Seminole Blvd...",0x88c2fb8614e57ce9:0x40b51628875ad6e9,NaN,27.834885,-82.787419,NaN,3.6,8,$$,NaN,NaN,NaN,Seminole,FL,33772

In [36]:
print(metdat_florida.iloc[11776]['address']) #['address']
print(type(metdat_florida.iloc[11776]['address'])) #['address']

SanCap Pak-N-Ship, 2422 Palm Ridge Rd, Sanibel, FL 33957
<class 'str'>

In [37]:

# FILTRO POR CODIGO POSTAL

metdat_florida['postal_code'] = pd.to_numeric(metdat_florida['postal_code'], errors='coerce') # metdat_florida

metdat_florida = metdat_florida[(metdat_florida['postal_code'] >= 32003) & (metdat_florida['postal_code'] <= 34997)].copy()
# According to website https://www.zipcode.com.ng/2022/06/list-of-florida-zip-codes-.html

In [38]:

# FILTRO POR CIUDADES FLORIDA

df_florida_cities = pd.read_json('/content/drive/MyDrive/Otros/us-cities-table-for-florida.json')
# Fuente Json https://worldpopulationreview.com/states/cities/florida

florida_names_list = df_florida_cities['name'].tolist()

metdat_florida = metdat_florida[metdat_florida['city'].isin(florida_names_list)]
metdat_florida.head(3)

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,city,states,postal_code
14,NTK OUTDOOR,"NTK OUTDOOR, 2315 NW 107th Ave #1B18, Miami, F...",0x88d9beb4fe0532c1:0xef0555c169299d6,NaN,25.795204,-80.366038,['Corporate office'],5.0,35,NaN,"[['Thursday', '9AM–6PM'], ['Friday', '9AM–6PM'...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 6PM,Miami,FL,33172.0
45,Cruises Inc. - Connie Stewart,"Cruises Inc. - Connie Stewart, 6602 52nd Ln, P...",0x88c2e49b79f06c31:0x4ed8c8ce27e926e0,NaN,27.832187,-82.704805,['Cruise agency'],5.0,2,NaN,"[['Thursday', '9AM–5PM'], ['Friday', '9AM–5PM'...",NaN,Open ⋅ Closes 5PM,Pinellas Park,FL,33781.0
56,Seminole Family Restaurant,"Seminole Family Restaurant, 6864 Seminole Blvd...",0x88c2fb8614e57ce9:0x40b51628875ad6e9,NaN,27.834885,-82.787419,NaN,3.6,8,$$,NaN,NaN,NaN,Seminole,FL,33772.0

## 3. Columna Category

In [39]:
# Le damos el formato adecuado a la columna category:

import numpy as np
import ast

metdat_florida['category'] = metdat_florida['category'].apply(lambda x: ast.literal_eval(x)
                                                                if isinstance(x, str) else np.nan)

def format_category_list(category_list):
    if isinstance(category_list, list):
        return ', '.join(category_list)
    else:
        return category_list

metdat_florida['category'] = metdat_florida['category'].apply(format_category_list)
metdat_florida.head(3)

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,city,states,postal_code
14,NTK OUTDOOR,"NTK OUTDOOR, 2315 NW 107th Ave #1B18, Miami, F...",0x88d9beb4fe0532c1:0xef0555c169299d6,NaN,25.795204,-80.366038,Corporate office,5.0,35,NaN,"[['Thursday', '9AM–6PM'], ['Friday', '9AM–6PM'...",{'Accessibility': ['Wheelchair accessible entr...,Open ⋅ Closes 6PM,Miami,FL,33172.0
45,Cruises Inc. - Connie Stewart,"Cruises Inc. - Connie Stewart, 6602 52nd Ln, P...",0x88c2e49b79f06c31:0x4ed8c8ce27e926e0,NaN,27.832187,-82.704805,Cruise agency,5.0,2,NaN,"[['Thursday', '9AM–5PM'], ['Friday', '9AM–5PM'...",NaN,Open ⋅ Closes 5PM,Pinellas Park,FL,33781.0
56,Seminole Family Restaurant,"Seminole Family Restaurant, 6864 Seminole Blvd...",0x88c2fb8614e57ce9:0x40b51628875ad6e9,NaN,27.834885,-82.787419,NaN,3.6,8,$$,NaN,NaN,NaN,Seminole,FL,33772.0

In [40]:
metdat_florida['category'].value_counts().sum()

186693

In [41]:
#states_list = ['FL']

#metdat_florida = metdat_florida[metdat_florida['states'].isin(states_list)] # ISIN es un filtro mas especifico(excluye otros terminos y filtra solo para lo indicado)
                                                                              #que CONTAINS(incluye a todos aquellos que tengan la palabra Restaurant por ejemplo)

#business_list = ['Restaurant']

metdat_florida['category'].fillna('', inplace=True)
metdat_florida = metdat_florida[metdat_florida['category'].str.contains('Restaurant')]
#metdat_florida = metdat_florida[metdat_florida['category'].isin(business_list)]
metdat_florida#.head(3)

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,city,states,postal_code
114,Cape Seafood Shack,"Cape Seafood Shack, 603 Del Prado Blvd S, Cape...",0x88db4147b1d9e6f3:0x943dbd10a92ba1b1,NaN,26.641377,-81.940545,Restaurant,5.0,1,$$,NaN,"{'Service options': ['Dine-in', 'Delivery'], '...",NaN,Cape Coral,FL,33990.0
674,Hot Box,"Hot Box, 1-99 Kinkaid St, Pensacola, FL 32507",0x8890b9241e704667:0x3a1e565c17c00993,NaN,30.391411,-87.267220,Restaurant,4.2,5,NaN,"[['Thursday', '6:30AM–6PM'], ['Friday', '6:30A...",{'Service options': ['Delivery']},Permanently closed,Pensacola,FL,32507.0
904,Gormley's on the river | Modern cuisine in his...,Gormley's on the river | Modern cuisine in his...,0x8894b5a7a7909725:0xe4687299fd288188,NaN,29.726949,-84.981535,"Modern French restaurant, Restaurant",4.3,17,NaN,"[['Thursday', '5–9PM'], ['Friday', '5–10PM'], ...",{'Service options': ['Delivery']},Permanently closed,Apalachicola,FL,32320.0
1165,Kala' Bites & Brews,"Kala' Bites & Brews, 17100 Gulf Blvd, North Re...",0x88c2fea614c52c8b:0x50e166caa05e8c0f,NaN,27.819094,-82.825162,"Bar, Beer store, Restaurant",5.0,2,NaN,"[['Thursday', '4–9PM'], ['Friday', '4–10PM'], ...","{'Service options': ['Delivery'], 'Highlights'...",Permanently closed,North Redington Beach,FL,33708.0
2438,Bachata Rosa,"Bachata Rosa, 887w W 29th St, Hialeah, FL 33012",0x88d9ba5d65937567:0xbc27649cf513cc89,NaN,25.848173,-80.299773,Restaurant,3.6,8,NaN,"[['Thursday', '6PM–1AM'], ['Friday', '6PM–1AM'...","{'Service options': ['Dine-in', 'Delivery'], '...",Closed ⋅ Opens 6PM,Hialeah,FL,33012.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3024652,Pizza Hut,"Pizza Hut, 17624 SW 137th Ave, Miami, FL 33186",0x88d9c2272a3c4b2d:0x2437f9b457f12896,Family-friendly chain known for its made-to-or...,25.604078,-80.414474,"Pizza restaurant, Chicken wings restaurant, Fa...",3.7,158,$,NaN,"{'Service options': ['Curbside pickup', 'No-co...",NaN,Miami,FL,33186.0
3024681,Bakery Antojitos Colombianos,"Bakery Antojitos Colombianos, 12161 SW 152nd S...",0x88d9c3c682fe8a01:0x34f123db79ec201e,NaN,25.627098,-80.389759,Restaurant,4.5,46,NaN,"[['Monday', '7:30AM–5PM'], ['Tuesday', '7:30AM...","{'Service options': ['Takeout', 'Delivery'], '...",Permanently closed,Miami,FL,33177.0
3024822,Chef Tian Express,"Chef Tian Express, 4700 S Le Jeune Rd, Miami, ...",0x88d9b7ef11cf0b9f:0x4b00c189182fb618,Familiar Chinese dinners & lunch specials offe...,25.728680,-80.262089,"Chinese restaurant, Asian restaurant, Restaurant",3.8,94,$,"[['Monday', '11AM–10PM'], ['Tuesday', '11AM–10...","{'Service options': ['No-contact delivery', 'D...",Opens soon ⋅ 11AM,Miami,FL,33146.0
3024947,Royal Bavarian Schnitzel Haus,"Royal Bavarian Schnitzel Haus, 1085 NE 79th St...",0x88d9b3cd3f274101:0x64335c60e4e3065e,Old-world Bavarian food hall with a menu of tr...,25.848295,-80.174799,"German restaurant, Bar, Restaurant",4.3,144,$$,"[['Monday', '5–11PM'], ['Tuesday', '6–11PM'], ...","{'Service options': ['Delivery'], 'Amenities':...",Permanently closed,Miami,FL,33138.0
3024980,Subpreme Grill,"Subpreme Grill, 15260 SW 280th St UNIT 111, Ho...",0x88d9dd6e78851851:0x849dcf273582261c,NaN,25.506121,-80.438215,"Sandwich shop, Fast food restaurant, Takeout R...",4.3,393,$,"[['Monday', '10AM–8PM'], ['Tuesday', '10AM–8PM...","{'Service options': ['Takeout'], 'Popular for'...",Open ⋅ Closes 8PM,Homestead,FL,33032.0

In [42]:
# Realizamos un conteo del top 10 de categorias:

category = metdat_florida['category'].str.split(', ').explode()
category_counts = category.value_counts()/len(metdat_florida)

# Mostrar el conteo de 24 categorías mas importantes
category_counts.head(24)

Restaurant                0.856829
Takeout Restaurant        0.175232
Fast food restaurant      0.125884
Sandwich shop             0.115826
Caterer                   0.093667
Delivery Restaurant       0.087694
Pizza restaurant          0.067578
Bar                       0.046205
American restaurant       0.046047
Breakfast restaurant      0.042118
Italian restaurant        0.035046
Coffee shop               0.033789
Pizza delivery            0.033160
Cafe                      0.030646
Bakery                    0.029703
Chinese restaurant        0.027031
Pizza Takeout             0.026717
Seafood restaurant        0.026717
Hamburger restaurant      0.024831
Juice shop                0.024202
Bar & grill               0.022474
Deli                      0.021688
Health food restaurant    0.020902
Convenience store         0.020116
Name: category, dtype: float64

In [43]:
top_category_names = category_counts.head(24).index.tolist()
top_category_names

['Restaurant',
 'Takeout Restaurant',
 'Fast food restaurant',
 'Sandwich shop',
 'Caterer',
 'Delivery Restaurant',
 'Pizza restaurant',
 'Bar',
 'American restaurant',
 'Breakfast restaurant',
 'Italian restaurant',
 'Coffee shop',
 'Pizza delivery',
 'Cafe',
 'Bakery',
 'Chinese restaurant',
 'Pizza Takeout',
 'Seafood restaurant',
 'Hamburger restaurant',
 'Juice shop',
 'Bar & grill',
 'Deli',
 'Health food restaurant',
 'Convenience store']

## 4. Columna MISC

In [44]:
print(metdat_florida.iloc[3]['MISC'])
print(type(metdat_florida.iloc[3]['MISC']))

{'Service options': ['Delivery'], 'Highlights': ['Fast service', 'Great bar food', 'Great beer selection', 'Sports'], 'Accessibility': ['Wheelchair accessible entrance', 'Wheelchair accessible restroom'], 'Offerings': ['Alcohol', 'Beer', 'Cocktails', 'Food', 'Food at bar', 'Wine'], 'Dining options': ['Seating'], 'Amenities': ['Restroom'], 'Atmosphere': ['Casual'], 'Crowd': ['Groups'], 'Planning': ['Accepts reservations'], 'Payments': ['Debit cards']}
<class 'str'>

In [45]:
print(metdat_florida.iloc[12]['MISC'])
print(type(metdat_florida.iloc[12]['MISC']))

{'Service options': ['Delivery'], 'Highlights': ['Great dessert'], 'Accessibility': ['Wheelchair accessible entrance', 'Wheelchair accessible parking lot', 'Wheelchair accessible seating'], 'Offerings': ['All you can eat', 'Coffee', 'Comfort food', 'Healthy options'], 'Dining options': ['Breakfast', 'Lunch', 'Dinner'], 'Amenities': ['Good for kids'], 'Atmosphere': ['Casual'], 'Crowd': ['Groups']}
<class 'str'>

## Lista de miscelaneos

'Service options': ['Takeout', 'Dine-in', 'Delivery']

'Highlights': ['Live music']

'Popular for': ['Lunch']

'Accessibility': ['Wheelchair accessible entrance']

'Offerings': ['Healthy options', 'Quick bite']

'Dining options': ['Breakfast', 'Lunch', 'Dinner', 'Seating']

'Crowd': ['Family-friendly']

'Atmosphere': ['Casual']

'Payments': ['Checks', 'Debit cards', 'NFC mobile payments', 'Credit cards']

'Amenities': ['Public restroom']

'Service options': ['No-contact delivery', 'Delivery', 'In-store shopping', 'Same-day delivery']

'Planning': ['Quick visit']

In [46]:
metdat_florida['MISC'] = metdat_florida['MISC'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else np.nan)

desired_keys = ['Service options','Highlights','Popular for','Accessibility','Offerings','Dining options','Crowd','Atmosphere','Payments','Amenities','Service options','Planning']

def extract_key_values(misc_dict, key):
    if isinstance(misc_dict, dict) and key in misc_dict:
        return ', '.join(misc_dict[key])
    else:
        return np.nan

# creamos columnas por cada key
for key in desired_keys:
    metdat_florida[key] = metdat_florida['MISC'].apply(lambda x: extract_key_values(x, key))

# Drop the 'MISC'
metdat_florida = metdat_florida.drop(columns=['MISC'])

metdat_florida

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,...,Highlights,Popular for,Accessibility,Offerings,Dining options,Crowd,Atmosphere,Payments,Amenities,Planning
114,Cape Seafood Shack,"Cape Seafood Shack, 603 Del Prado Blvd S, Cape...",0x88db4147b1d9e6f3:0x943dbd10a92ba1b1,NaN,26.641377,-81.940545,Restaurant,5.0,1,$$,...,NaN,NaN,"Wheelchair accessible entrance, Wheelchair acc...",Comfort food,"Lunch, Dinner",NaN,Casual,NaN,Good for kids,NaN
674,Hot Box,"Hot Box, 1-99 Kinkaid St, Pensacola, FL 32507",0x8890b9241e704667:0x3a1e565c17c00993,NaN,30.391411,-87.267220,Restaurant,4.2,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
904,Gormley's on the river | Modern cuisine in his...,Gormley's on the river | Modern cuisine in his...,0x8894b5a7a7909725:0xe4687299fd288188,NaN,29.726949,-84.981535,"Modern French restaurant, Restaurant",4.3,17,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1165,Kala' Bites & Brews,"Kala' Bites & Brews, 17100 Gulf Blvd, North Re...",0x88c2fea614c52c8b:0x50e166caa05e8c0f,NaN,27.819094,-82.825162,"Bar, Beer store, Restaurant",5.0,2,NaN,...,"Fast service, Great bar food, Great beer selec...",NaN,"Wheelchair accessible entrance, Wheelchair acc...","Alcohol, Beer, Cocktails, Food, Food at bar, Wine",Seating,Groups,Casual,Debit cards,Restroom,Accepts reservations
2438,Bachata Rosa,"Bachata Rosa, 887w W 29th St, Hialeah, FL 33012",0x88d9ba5d65937567:0xbc27649cf513cc89,NaN,25.848173,-80.299773,Restaurant,3.6,8,NaN,...,NaN,"Lunch, Solo dining",Wheelchair accessible entrance,NaN,NaN,Groups,Casual,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3024652,Pizza Hut,"Pizza Hut, 17624 SW 137th Ave, Miami, FL 33186",0x88d9c2272a3c4b2d:0x2437f9b457f12896,Family-friendly chain known for its made-to-or...,25.604078,-80.414474,"Pizza restaurant, Chicken wings restaurant, Fa...",3.7,158,$,...,NaN,"Lunch, Dinner",Wheelchair accessible entrance,"Comfort food, Late-night food, Quick bite","Lunch, Dinner, Dessert",College students,Casual,Debit cards,Good for kids,NaN
3024681,Bakery Antojitos Colombianos,"Bakery Antojitos Colombianos, 12161 SW 152nd S...",0x88d9c3c682fe8a01:0x34f123db79ec201e,NaN,25.627098,-80.389759,Restaurant,4.5,46,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good for kids,NaN
3024822,Chef Tian Express,"Chef Tian Express, 4700 S Le Jeune Rd, Miami, ...",0x88d9b7ef11cf0b9f:0x4b00c189182fb618,Familiar Chinese dinners & lunch specials offe...,25.728680,-80.262089,"Chinese restaurant, Asian restaurant, Restaurant",3.8,94,$,...,NaN,"Lunch, Dinner, Solo dining",NaN,"Comfort food, Quick bite",NaN,NaN,"Casual, Cozy",NaN,Good for kids,NaN
3024947,Royal Bavarian Schnitzel Haus,"Royal Bavarian Schnitzel Haus, 1085 NE 79th St...",0x88d9b3cd3f274101:0x64335c60e4e3065e,Old-world Bavarian food hall with a menu of tr...,25.848295,-80.174799,"German restaurant, Bar, Restaurant",4.3,144,$$,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good for kids,NaN
3024980,Subpreme Grill,"Subpreme Grill, 15260 SW 280th St UNIT 111, Ho...",0x88d9dd6e78851851:0x849dcf273582261c,NaN,25.506121,-80.438215,"Sandwich shop, Fast food restaurant, Takeout R...",4.3,393,$,...,NaN,"Lunch, Dinner, Solo dining",Wheelchair accessible entrance,"Comfort food, Healthy options, Quick bite, Sma...",Dessert,"College students, Groups, Tourists","Casual, Cozy",NFC mobile payments,"Good for kids, High chairs",NaN

In [47]:
columns_to_iterate = ['Service options','Highlights','Popular for','Accessibility','Offerings','Dining options','Crowd','Atmosphere','Payments','Amenities','Service options','Planning']

for col in columns_to_iterate:
    value_counts = metdat_florida[col].value_counts()
    total_count = value_counts.sum()  # Calculate the sum of counts
    print(f"Value Counts for {col}:\n{value_counts}\nTotal Count: {total_count}\n")

Value Counts for Service options:
Delivery                                                        1448
Takeout, Delivery                                                670
Delivery, Takeout, Dine-in                                       585
Takeout, Dine-in, Delivery                                       444
Delivery, Takeout                                                305
                                                                ...
Outdoor seating, Curbside pickup, Dine-in, Delivery, Takeout       1
Delivery, In-store shopping, Takeout, Dine-in                      1
Curbside pickup, In-store pickup, In-store shopping, Dine-in       1
In-store pickup, Same-day delivery                                 1
Online appointments                                                1
Name: Service options, Length: 147, dtype: int64
Total Count: 6128

Value Counts for Highlights:
Fast service                                                               264
Great coffee                                                               252
Great dessert                                                              180
LGBTQ friendly, Transgender safespace                                      109
LGBTQ friendly                                                              83
                                                                          ...
Fast service, Great cocktails, Great wine list, LGBTQ friendly               1
Bar games, Fast service, Great bar food, Great cocktails, Sports             1
Great beer selection, LGBTQ friendly, Live music, Transgender safespace      1
Fireplace, Great coffee, Great dessert, Great tea selection, Live music      1
Great dessert, Sports                                                        1
Name: Highlights, Length: 305, dtype: int64
Total Count: 2010

Value Counts for Popular for:
Lunch, Dinner, Solo dining                                           1841
Lunch, Solo dining                                                    334
Solo dining                                                           311
Dinner, Solo dining                                                   235
Breakfast, Lunch, Solo dining                                         231
Breakfast, Lunch, Dinner, Solo dining                                 203
Lunch, Dinner                                                         168
Breakfast, Solo dining                                                 62
Lunch                                                                  52
Dinner                                                                 39
Breakfast, Solo dining, Good for working on laptop                     24
Breakfast, Lunch                                                       13
Breakfast, Lunch, Solo dining, Good for working on laptop              10
Breakfast, Lunch, Dinner                                               10
Breakfast                                                               8
Breakfast, Dinner, Solo dining                                          3
Lunch, Solo dining, Good for working on laptop                          3
Breakfast, Lunch, Dinner, Solo dining, Good for working on laptop       3
Lunch, Dinner, Solo dining, Good for working on laptop                  1
Name: Popular for, dtype: int64
Total Count: 3551

Value Counts for Accessibility:
Wheelchair accessible entrance                                                                                                                                      3175
Wheelchair accessible entrance, Wheelchair accessible parking lot, Wheelchair accessible restroom, Wheelchair accessible seating                                     386
Wheelchair accessible entrance, Wheelchair accessible parking lot, Wheelchair accessible seating                                                                     279
Wheelchair accessible entrance, Wheelchair accessible restroom                                                                                                       272
Wheelchair accessible entrance, Wheelchair accessible parking lot                                                                                                    166
Wheelchair accessible entrance, Wheelchair accessible seating                                                                                                        144
Wheelchair accessible entrance, Wheelchair accessible parking lot, Wheelchair accessible restroom                                                                     81
Wheelchair accessible entrance, Wheelchair accessible restroom, Wheelchair accessible seating                                                                         69
Wheelchair accessible elevator, Wheelchair accessible entrance, Wheelchair accessible parking lot, Wheelchair accessible restroom, Wheelchair accessible seating      61
Wheelchair accessible seating                                                                                                                                         53
Wheelchair accessible restroom                                                                                                                                        44
Wheelchair accessible parking lot                                                                                                                                     39
Wheelchair accessible parking lot, Wheelchair accessible seating                                                                                                      20
Wheelchair accessible parking lot, Wheelchair accessible restroom, Wheelchair accessible seating                                                                      16
Wheelchair accessible elevator, Wheelchair accessible entrance, Wheelchair accessible parking lot, Wheelchair accessible restroom                                     11
Wheelchair accessible elevator, Wheelchair accessible entrance                                                                                                         9
Wheelchair accessible entrance, Wheelchair accessible parking lot, Wheelchair accessible seating, Wheelchair accessible restroom                                       7
Wheelchair accessible elevator, Wheelchair accessible entrance, Wheelchair accessible parking lot                                                                      6
Wheelchair accessible elevator, Wheelchair accessible entrance, Wheelchair accessible restroom, Wheelchair accessible seating                                          5
Wheelchair accessible restroom, Wheelchair accessible seating                                                                                                          4
Wheelchair accessible elevator                                                                                                                                         4
Wheelchair accessible elevator, Wheelchair accessible entrance, Wheelchair accessible restroom                                                                         3
Wheelchair accessible restroom, Wheelchair accessible entrance                                                                                                         3
Wheelchair accessible parking lot, Wheelchair accessible restroom                                                                                                      3
Wheelchair accessible parking lot, Wheelchair accessible restroom, Wheelchair accessible seating, Wheelchair accessible entrance                                       2
Wheelchair accessible entrance, Wheelchair accessible seating, Wheelchair accessible parking lot                                                                       1
Wheelchair accessible parking lot, Wheelchair accessible seating, Wheelchair accessible entrance                                                                       1
Wheelchair accessible entrance, Wheelchair accessible seating, Wheelchair accessible restroom                                                                          1
Wheelchair accessible elevator, Wheelchair accessible restroom                                                                                                         1
Wheelchair accessible elevator, Wheelchair accessible entrance, Wheelchair accessible parking lot, Wheelchair accessible seating                                       1
Wheelchair accessible elevator, Wheelchair accessible entrance, Wheelchair accessible seating                                                                          1
Name: Accessibility, dtype: int64
Total Count: 4868

Value Counts for Offerings:
Comfort food, Quick bite                                                                                             449
Comfort food, Quick bite, Small plates                                                                               292
Comfort food                                                                                                         196
Comfort food, Healthy options, Kids' menu, Quick bite, Vegetarian options                                            129
Coffee, Comfort food, Quick bite, Small plates                                                                       113
                                                                                                                    ...
Alcohol, Beer, Cocktails, Coffee, Comfort food, Healthy options, Kids' menu, Quick bite, Vegetarian options, Wine      1
Coffee, Comfort food, Happy hour food, Kids' menu, Late-night food, Quick bite, Small plates                           1
Alcohol, Beer, Healthy options, Vegetarian options                                                                     1
Alcohol, Beer, Cocktails, Coffee, Comfort food, Happy hour food, Hard liquor, Wine                                     1
Beer, Coffee, Comfort food, Healthy options, Quick bite, Small plates, Vegetarian options                              1
Name: Offerings, Length: 1236, dtype: int64
Total Count: 4721

Value Counts for Dining options:
Dessert                                                                     1031
Lunch, Dinner                                                                420
Lunch, Dinner, Catering, Dessert, Seating                                    215
Lunch, Dinner, Dessert                                                       188
Breakfast, Lunch, Dinner, Catering, Dessert, Seating                         162
                                                                            ...
Lunch, Counter service, Dessert                                                1
Breakfast, Counter service, Dessert                                            1
Breakfast, Lunch, Dinner, Catering, Counter service                            1
Breakfast, Catering, Dessert                                                   1
Breakfast, Lunch, Catering, Counter service, Dessert, Pay ahead, Seating       1
Name: Dining options, Length: 85, dtype: int64
Total Count: 3774

Value Counts for Crowd:
Groups                                                 890
Groups, Tourists                                       620
Family-friendly                                        484
Tourists                                               318
Family-friendly, Groups, Tourists                      250
Family-friendly, Groups                                171
College students, Groups, Tourists                     153
Family-friendly, Tourists                              105
Groups, Locals                                          93
College students, Groups                                68
Locals                                                  56
College students, Family-friendly, Groups, Tourists     49
College students                                        44
College students, Tourists                              39
Groups, Locals, Tourists                                29
College students, Family-friendly, Groups               16
College students, Family-friendly, Tourists             16
College students, Family-friendly                       15
College students, Groups, Locals                        10
College students, Groups, Locals, Tourists               3
Locals, Tourists                                         3
Family-friendly, Groups, Locals, Tourists                2
College students, Locals                                 2
Family-friendly, Groups, Locals                          2
Name: Crowd, dtype: int64
Total Count: 3438

Value Counts for Atmosphere:
Casual                                       2535
Casual, Cozy                                 1305
Casual, Quiet                                  53
Cozy                                           30
Casual, Cozy, Quiet                            30
Cozy, Romantic, Upscale                        20
Casual, Cozy, Romantic                         19
Cozy, Romantic                                 14
Casual, Cozy, Romantic, Upscale                13
Casual, Cozy, Upscale                          10
Trending                                        6
Casual, Historic                                5
Casual, Cozy, Historic                          4
Casual, Cozy, Trending                          4
Casual, Cozy, Quiet, Romantic                   3
Cozy, Upscale                                   3
Casual, Cozy, Historic, Romantic                3
Romantic                                        3
Casual, Romantic                                2
Casual, Romantic, Upscale                       2
Cozy, Historic, Romantic, Upscale               2
Casual, Trending                                2
Historic                                        2
Casual, Upscale                                 2
Romantic, Upscale                               1
Quiet, Romantic, Upscale                        1
Casual, Quiet, Romantic                         1
Casual, Cozy, Historic, Quiet                   1
Casual, Cozy, Quiet, Romantic, Upscale          1
Casual, Cozy, Historic, Romantic, Upscale       1
Name: Atmosphere, dtype: int64
Total Count: 4078

Value Counts for Payments:
Debit cards                                                          648
Debit cards, NFC mobile payments                                     493
Debit cards, Credit cards                                            435
NFC mobile payments                                                  372
Debit cards, NFC mobile payments, Credit cards                       294
Credit cards                                                          74
NFC mobile payments, Credit cards                                     42
Checks, Debit cards, Credit cards                                     36
Cash-only                                                             34
Checks, Debit cards, NFC mobile payments, Credit cards                27
Cash-only, Debit cards                                                25
Checks, Debit cards                                                   20
Cash-only, Debit cards, Credit cards                                  15
Checks, Debit cards, NFC mobile payments                              11
Cash-only, NFC mobile payments, Credit cards                           7
Cash-only, Debit cards, NFC mobile payments, Credit cards              7
Cash-only, NFC mobile payments                                         5
Cash-only, Debit cards, NFC mobile payments                            5
Checks                                                                 4
Cash-only, Checks, Debit cards, Credit cards                           3
Cash-only, Credit cards                                                2
Cash-only, Checks, Debit cards                                         2
Checks, Credit cards                                                   1
Cash-only, Checks                                                      1
Cash-only, Checks, NFC mobile payments                                 1
Cash-only, Checks, Debit cards, NFC mobile payments, Credit cards      1
Name: Payments, dtype: int64
Total Count: 2565

Value Counts for Amenities:
Good for kids                                                2460
Bar onsite                                                    285
Good for kids, High chairs                                    265
Good for kids, Restroom                                       242
Good for kids, High chairs, Restroom                          178
                                                             ...
Gender-neutral restroom, High chairs                            1
Bar onsite, Gender-neutral restroom, High chairs                1
Gender-neutral restroom, High chairs, Restroom, Wi-Fi           1
Bar onsite, Gender-neutral restroom, Good for kids, Wi-Fi       1
Gender-neutral restroom, Public restroom, Restroom              1
Name: Amenities, Length: 66, dtype: int64
Total Count: 4910

Value Counts for Service options:
Delivery                                                        1448
Takeout, Delivery                                                670
Delivery, Takeout, Dine-in                                       585
Takeout, Dine-in, Delivery                                       444
Delivery, Takeout                                                305
                                                                ...
Outdoor seating, Curbside pickup, Dine-in, Delivery, Takeout       1
Delivery, In-store shopping, Takeout, Dine-in                      1
Curbside pickup, In-store pickup, In-store shopping, Dine-in       1
In-store pickup, Same-day delivery                                 1
Online appointments                                                1
Name: Service options, Length: 147, dtype: int64
Total Count: 6128

Value Counts for Planning:
Accepts reservations                                                                     771
Quick visit                                                                              138
Dinner reservations recommended, Accepts reservations                                     69
Usually a wait                                                                            15
Dinner reservations recommended                                                            5
Dinner reservations recommended, Accepts reservations, Usually a wait                      3
Accepts reservations, Usually a wait                                                       2
Appointments recommended                                                                   1
Lunch reservations recommended, Dinner reservations recommended, Accepts reservations      1
Lunch reservations recommended, Accepts reservations                                       1
Membership required                                                                        1
Name: Planning, dtype: int64
Total Count: 1007

In [48]:
metdat_florida.drop(columns=['Planning', 'Payments', 'Highlights'], inplace=True)

## 5. Columna Hours

In [49]:
print(metdat_florida.iloc[3]['hours'])
print(type(metdat_florida.iloc[3]['hours']))

[['Thursday', '4–9PM'], ['Friday', '4–10PM'], ['Saturday', '4–10PM'], ['Sunday', '4–9PM'], ['Monday', 'Closed'], ['Tuesday', '4–9PM'], ['Wednesday', '4–9PM']]
<class 'str'>

In [ ]:
import ast
# De <class 'str'> a <class 'list'>

metdat_florida['hours'] = metdat_florida['hours'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else None)

# De <class 'list'> a <class 'dict'>

metdat_florida['hours'] = metdat_florida['hours'].apply(lambda x: dict(x) if isinstance(x, list) else None)

# De <class 'dict'> a columnas

hours_df = metdat_florida['hours'].apply(pd.Series)

# Concatenamos las columnas

metdat_florida = pd.concat([metdat_florida, hours_df], axis=1)

#metdat_florida = metdat_florida.drop(columns=['hours', 0])

metdat_florida.head(3)

In [51]:
metdat_florida.iloc[0]

name                                              Cape Seafood Shack
address            Cape Seafood Shack, 603 Del Prado Blvd S, Cape...
gmap_id                        0x88db4147b1d9e6f3:0x943dbd10a92ba1b1
description                                                      NaN
latitude                                                   26.641377
longitude                                                 -81.940545
category                                                  Restaurant
avg_rating                                                       5.0
num_of_reviews                                                     1
price                                                             $$
hours                                                           None
state                                                            NaN
city                                                      Cape Coral
states                                                            FL
postal_code                                                  33990.0
Service options                                    Dine-in, Delivery
Popular for                                                      NaN
Accessibility      Wheelchair accessible entrance, Wheelchair acc...
Offerings                                               Comfort food
Dining options                                         Lunch, Dinner
Crowd                                                            NaN
Atmosphere                                                    Casual
Amenities                                              Good for kids
Thursday                                                         NaN
Friday                                                           NaN
Saturday                                                         NaN
Sunday                                                           NaN
Monday                                                           NaN
Tuesday                                                          NaN
Wednesday                                                        NaN
Name: 114, dtype: object

In [52]:
metdat_florida.fillna('sin datos')

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,...,Crowd,Atmosphere,Amenities,Thursday,Friday,Saturday,Sunday,Monday,Tuesday,Wednesday
114,Cape Seafood Shack,"Cape Seafood Shack, 603 Del Prado Blvd S, Cape...",0x88db4147b1d9e6f3:0x943dbd10a92ba1b1,sin datos,26.641377,-81.940545,Restaurant,5.0,1,$$,...,sin datos,Casual,Good for kids,sin datos,sin datos,sin datos,sin datos,sin datos,sin datos,sin datos
674,Hot Box,"Hot Box, 1-99 Kinkaid St, Pensacola, FL 32507",0x8890b9241e704667:0x3a1e565c17c00993,sin datos,30.391411,-87.267220,Restaurant,4.2,5,sin datos,...,sin datos,sin datos,sin datos,6:30AM–6PM,6:30AM–6PM,6:30AM–6PM,Closed,6:30AM–6PM,6:30AM–6PM,6:30AM–6PM
904,Gormley's on the river | Modern cuisine in his...,Gormley's on the river | Modern cuisine in his...,0x8894b5a7a7909725:0xe4687299fd288188,sin datos,29.726949,-84.981535,"Modern French restaurant, Restaurant",4.3,17,sin datos,...,sin datos,sin datos,sin datos,5–9PM,5–10PM,5–10PM,5–9PM,Closed,Closed,5–9PM
1165,Kala' Bites & Brews,"Kala' Bites & Brews, 17100 Gulf Blvd, North Re...",0x88c2fea614c52c8b:0x50e166caa05e8c0f,sin datos,27.819094,-82.825162,"Bar, Beer store, Restaurant",5.0,2,sin datos,...,Groups,Casual,Restroom,4–9PM,4–10PM,4–10PM,4–9PM,Closed,4–9PM,4–9PM
2438,Bachata Rosa,"Bachata Rosa, 887w W 29th St, Hialeah, FL 33012",0x88d9ba5d65937567:0xbc27649cf513cc89,sin datos,25.848173,-80.299773,Restaurant,3.6,8,sin datos,...,Groups,Casual,sin datos,6PM–1AM,6PM–1AM,6PM–1AM,6PM–1AM,6PM–1AM,6PM–1AM,Closed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3024652,Pizza Hut,"Pizza Hut, 17624 SW 137th Ave, Miami, FL 33186",0x88d9c2272a3c4b2d:0x2437f9b457f12896,Family-friendly chain known for its made-to-or...,25.604078,-80.414474,"Pizza restaurant, Chicken wings restaurant, Fa...",3.7,158,$,...,College students,Casual,Good for kids,sin datos,sin datos,sin datos,sin datos,sin datos,sin datos,sin datos
3024681,Bakery Antojitos Colombianos,"Bakery Antojitos Colombianos, 12161 SW 152nd S...",0x88d9c3c682fe8a01:0x34f123db79ec201e,sin datos,25.627098,-80.389759,Restaurant,4.5,46,sin datos,...,sin datos,sin datos,Good for kids,7:30AM–5PM,7:30AM–5PM,7:30AM–5PM,Closed,7:30AM–5PM,7:30AM–5PM,7:30AM–5PM
3024822,Chef Tian Express,"Chef Tian Express, 4700 S Le Jeune Rd, Miami, ...",0x88d9b7ef11cf0b9f:0x4b00c189182fb618,Familiar Chinese dinners & lunch specials offe...,25.728680,-80.262089,"Chinese restaurant, Asian restaurant, Restaurant",3.8,94,$,...,sin datos,"Casual, Cozy",Good for kids,11AM–10PM,11AM–10PM,12–10:30PM,4–10PM,11AM–10PM,11AM–10PM,11AM–10PM
3024947,Royal Bavarian Schnitzel Haus,"Royal Bavarian Schnitzel Haus, 1085 NE 79th St...",0x88d9b3cd3f274101:0x64335c60e4e3065e,Old-world Bavarian food hall with a menu of tr...,25.848295,-80.174799,"German restaurant, Bar, Restaurant",4.3,144,$$,...,sin datos,sin datos,Good for kids,6–11PM,6–11PM,6–11PM,6–11PM,5–11PM,6–11PM,6–11PM
3024980,Subpreme Grill,"Subpreme Grill, 15260 SW 280th St UNIT 111, Ho...",0x88d9dd6e78851851:0x849dcf273582261c,sin datos,25.506121,-80.438215,"Sandwich shop, Fast food restaurant, Takeout R...",4.3,393,$,...,"College students, Groups, Tourists","Casual, Cozy","Good for kids, High chairs",10AM–8PM,10AM–8PM,10AM–8PM,10AM–7PM,10AM–8PM,10AM–8PM,10AM–8PM

In [53]:
metdat_florida.to_csv('/content/drive/MyDrive/Otros/googlemaps_metadata_sitios_florida.csv', index=False)

In [54]:
metdat_florida['price'].value_counts()

$       1566
$$       982
$$$       38
$$$$       4
Name: price, dtype: int64

# Author: Max J.